### ISSUE TITLE
[DOC] - Add information about role heirarchy

### ISSUE THREAD

**Issue by nhcarrigan** [BeccaLyria/discord-documentation#525]
### What is incorrect in the documentation?

The documentation currently does not cover the fact that Becca's Discord role must be higher than any of the self-assignable roles.

### What should that text say?

Within the configure your server command, we should probably detail the required Discord permissions overall (the invite link lists the needed permissions).

### Additional information

We can refer readers to the Discord support article for this too: https://support.discord.com/hc/en-us/articles/214836687-Role-Management-101

**Comment by Panquesito7** [comment]
May I work on this issue? Thanks. 🙂

**Comment by nhcarrigan** [comment]
This is something I will likely handle myself, just because of the nature of Discord permissions and the familiarity with the bot that is required.
