### ISSUE TITLE
[DOC] - Rename `/becca becca` command.

### ISSUE THREAD

**Issue by nhcarrigan** [BeccaLyria/discord-documentation#552]
### What is incorrect in the documentation?

Under the Manual Commands page, the `/becca` section has a command called `becca`. This has been renamed.

### What should that text say?

The `command` value in the table should be changed to `profile`, and should be placed in the correct alphabetical position.

**Comment by kkhitesh** [comment]
Hey, I would like to work on this

**Comment by nhcarrigan** [comment]
Hi @kkhitesh, 

Thanks for your interest in contributing! We already have an approved PR that fixes this issue (it will be merged when the bot changes deploy)
