### ISSUE TITLE
[DOC] - `OWNER_ID` should be required

### ISSUE THREAD

**Issue by nhcarrigan** [BeccaLyria/discord-documentation#558]
### What is incorrect in the documentation?

The `OWNER_ID` is marked as `optional` in the `setup-code.md` steps.

### What should that text say?

This value should be changed to `required`.

### Additional information

Related to https://github.com/BeccaLyria/discord-bot/issues/870.

**Comment by ankeshp03** [comment]
Hi @nhcarrigan, if this issue is not assigned, can you please assign this to me?

**Comment by nhcarrigan** [comment]
All yours!
