### ISSUE TITLE
[DOC] - Developer Certificate of Origin

### ISSUE THREAD

**Issue by nhcarrigan** [BeccaLyria/discord-documentation#560]
### What is incorrect in the documentation?

The Developer Certificate of Origin is currently not present in the contributing documentation.

### What should that text say?

A new file should be added in the `docs` directory called `developer-certificate.md`.

The text within should be the text of the [Developer Certificate of Origin](https://developercertificate.org/).

### Additional information

Must be done before https://github.com/BeccaLyria/discord-bot/issues/869

**Comment by Panquesito7** [comment]
May I work on this?

**Comment by KanhaKorgaonkar** [comment]
Hi! I would like to work on this for Hacktoberfest, so please assign this issue to me. Thanks!

**Comment by nhcarrigan** [comment]
All yours!

**Comment by KanhaKorgaonkar** [comment]
Hi @nhcarrigan; thank you for assigning this issue to me, I have fixed it. Please review and give your feedback.
