### ISSUE TITLE
[BUG] - Update Habitica Status

### ISSUE THREAD

**Issue by krishguptadev** [BeccaLyria/discord-documentation#577]
### What bug did you encounter?

![image](https://user-images.githubusercontent.com/91655303/139568509-d966e58e-dc63-4f28-b25b-352f72f8a8b0.png)

### What did you expect to happen?

-

### Additional information

Would like to work on this? :D

**Comment by nhcarrigan** [comment]
This one and the `orbit` one both need to be updated.

Let's strike through the current text, and append "Restored in x.x.x" afterwards:

- ~~`habitica` command *(deprecated in 14.0.0) - Removed due to cognitive complexity, may restore with a new approach~~ Restored in 17.2.0

**Comment by krishguptadev** [comment]
Can I work on this as stated in the issue description?

**Comment by nhcarrigan** [comment]
All yours!
