### ISSUE TITLE
[DOC] - Add docs for the new commands

### ISSUE THREAD

**Issue by krishguptadev** [BeccaLyria/discord-documentation#578]
### What is incorrect in the documentation?

Update docs for:
![image](https://user-images.githubusercontent.com/91655303/139568550-e0b3189f-f9f9-4601-bf0e-0df23f15b8ab.png)

### What should that text say?

Check [this](#what-is-incorrect-in-the-documentation-)

**Comment by nhcarrigan** [comment]
These were updated in #576

**Comment by krishguptadev** [comment]
But I don't think the docs are enough 😅 like `habitica` where it is clearly not mentioned what habitica is :)

**Comment by nhcarrigan** [comment]
The people that would use this command are the people who already know what Habitica is. 🙂
