### ISSUE TITLE
[DOC] - Add documentation for the "Ban Appeal config" feature

### ISSUE THREAD

**Issue by Vyvy-vi** [BeccaLyria/discord-documentation#598]
### What work needs to be performed?

This would involve adding details similar to this on the ["Configure your Server" page](https://docs.beccalyria.com/#/configure-server):
| Setting | Value | Description |
| :-: | :-: | :-: |
| Ban Appeal Config | appeal_link: string | You can provide a link to a Google Form (or another service) for appealing a ban. This link is included in the DM sent to the banned user by Becca. |

**Comment by sabinbaniya** [comment]
Hey i want to work on this. Can you assign me?

**Comment by nhcarrigan** [comment]
Go for it!

**Comment by nhcarrigan** [comment]
Closed via #600
