### ISSUE TITLE
[DOC] - Update the date of Copyright

### ISSUE THREAD

**Issue by FahimFBA** [BeccaLyria/discord-documentation#619]
### What is incorrect in the documentation?

![image](https://user-images.githubusercontent.com/64195132/159852100-044b10ea-c550-4fd0-b30c-b6f27b5fe6bf.png)

The year is showing 2021.

### What should that text say?

Shouldn't it be 2022 as of now?

**Comment by TAKANOME-DEV** [comment]
Looks like the date of copyright need some update, could you attribute it to me 😊

**Comment by nhcarrigan** [comment]
Sure!

**Comment by FahimFBA** [comment]
I thought of doing that earlier, but after getting your reply, I thought that maybe you wanted to do that yourself. 😅
